CREATE TABLE IF NOT EXISTS global_bans (
  user_id BIGINT PRIMARY KEY,
  reason TEXT NOT NULL,
  actor_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS staff_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  guild_id BIGINT,
  actor_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tickets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  guild_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  claimed_by BIGINT,
  claimed_at TIMESTAMP
);
